### ISSUE TITLE
How to make discussions request?

### ISSUE THREAD

**Issue by LanShunoda** [busyorg/steem-api#7]
All discussion requests return nothing.
Like this https://api.steemjs.com/getDiscussionsByCreated it doen't work.
Does it need some parameters?
Adding query parameter like in js docs changes nothing 
https://api.steemjs.com/getDiscussionsByCreated?query=some

**Comment by adcpm** [comment]
I've commit a change on the API, it was not possible before to send an object in the url. Now its possible, you can query it like this: http://api.steemjs.com/getDiscussionsByCreated?query={"limit":"10","tag":"steemjs"}

**Comment by sneak** [comment]
that is clearly what POST is for and not get? alternately limit and/or tag should be their own query parameters instead of serialized under the query param.

**Comment by adcpm** [comment]
Afaik with POST you would not able to send an object without serialisation too. Also IMO using custom param like limit=10&tag=steemit would not be optimal, it would not work if with have a 2 levels object or if root param as same name than another level param. Another way to solve this would be to enable object param like this ?query.limit=10&query.tag=steemit

**Comment by andrienpecson** [comment]
How about getting discussions by author name?
